backend:
  name: git-gateway
  branch: main

media_folder: "Perspectivas/Analisis (pdf)"
public_folder: "/Perspectivas/Analisis (pdf)"

collections:
  - name: "perspectivas_list"
    label: "Lista de Análisis"
    files:
      - label: "Análisis Perspectivas"
        name: "analisis"
        file: "data/perspectivas.json"
        fields:
          - label: "Artículos"
            name: "perspectivas"
            widget: "list"
            allow_add: true
            fields:
              - { label: "ID", name: "id", widget: "string", hint: "Ej: 03" }
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Fecha", name: "fecha", widget: "string" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Archivo PDF", name: "pdf", widget: "file" }
